### ISSUE TITLE
Error when run 'run_experiment.py'

### ISSUE THREAD

**Issue by Auroradsy** [rjbruin/flexconv#7]
Thank you for your nice work and opensource codes!,

It seems that there is something wrong when using the 'srf' lib, the detailed problem is attached below.
![image](https://github.com/rjbruin/flexconv/assets/50282763/d7804f18-788f-4d2d-8d98-ddbb8736a90e)

**Comment by rjbruin** [comment]
Hi @Auroradsy, can you try to downgrade Python to 3.7 or earlier and see if that works?
